Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/jsonapi-serializers/attributes.rb'
    - 'lib/jsonapi-serializers/serializer.rb'

# Offense count: 6
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'spec/serializer_spec.rb'

# Offense count: 3
Lint/UselessAssignment:
  Exclude:
    - 'lib/jsonapi-serializers/serializer.rb'

# Offense count: 5
Metrics/AbcSize:
  Max: 102

# Offense count: 30
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 1137

# Offense count: 4
Metrics/CyclomaticComplexity:
  Max: 37

# Offense count: 5
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 77

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 225

# Offense count: 4
Metrics/PerceivedComplexity:
  Max: 38

# Offense count: 3
Style/ClassVars:
  Exclude:
    - 'lib/jsonapi-serializers/serializer.rb'

# Offense count: 1
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, AllowedAcronyms.
Style/FileName:
  Exclude:
    - 'lib/jsonapi-serializers.rb'

# Offense count: 7
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/jsonapi-serializers/attributes.rb'
    - 'lib/jsonapi-serializers/serializer.rb'
