Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

# Offense count: 5
Metrics/AbcSize:
  Max: 100

# Offense count: 30
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 945

# Offense count: 4
Metrics/CyclomaticComplexity:
  Max: 35

# Offense count: 5
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 74

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 215

# Offense count: 4
Metrics/PerceivedComplexity:
  Max: 36

# Offense count: 3
Style/ClassVars:
  Exclude:
    - 'lib/jsonapi-serializers/serializer/instance_methods.rb'

# Offense count: 1
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, AllowedAcronyms.
Style/FileName:
  Exclude:
    - 'lib/jsonapi-serializers.rb'

# Offense count: 7
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/jsonapi-serializers/attributes.rb'
    - 'lib/jsonapi-serializers/serializer.rb'
    - 'lib/jsonapi-serializers/serializer/instance_methods.rb'
